apiVersion: v1
kind: PersistentVolume
metadata:
  name: jefs-pv
  labels:
    name: jefs-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  nfs:
    server: "10.7.12.3"
    path: /volume1/k8s

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jefs-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: ""
  selector:
    matchLabels:
      name: jefs-pv

---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: c1
    image: sevendollar/web-golang
    ports:
    - name: http
      containerPort: 80
    resources:
        limits:
          cpu: "500m"
          memory: "500Mi"
    volumeMounts:
      - name: v1
        mountPath: /nfs
  volumes:
  - name: v1
    persistentVolumeClaim:
        claimName: jefs-pvc