apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jefs-first-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: c1
            image: sevendollar/k8s-job-test